# Generated by Django 3.0.6 on 2021-06-09 14:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0004_auto_20210609_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crossed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_list', models.CharField(blank=True, max_length=400, null=True, validators=[django.core.validators.int_list_validator])),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingo.Player')),
            ],
        ),
    ]
